### ISSUE TITLE
Add support for paged responses

### ISSUE THREAD

**Issue by mallocator** [machadogj/node-google-bigquery#5]
Querying for a large number of elements, e.g. for a list of all tables it can happen that google responds with a pages responds if you're over a certain threshold. The response then typically contains a "nextPageToken" property. 

Currently there is no obvious way to get the next page and the rest of the results. What's missing is either the implementation or somewhere some documentation/tests that show how we can get to the rest of the data.

**Comment by machadogj** [comment]
Thanks for the PR!
